/* nilam — build.
 *
 * Solves the palette, PROVES it, and only then writes the stylesheets. The order is the
 * point: a failing assertion aborts the build rather than emitting a palette that lies.
 *
 *   node build.mjs            solve hue 285, prove, emit
 *   node build.mjs 262        the same for another hue
 */

import { writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { solvePalette, solveSemanticHues, NILAM_HUE } from './src/solve.mjs';
import { prove, proveStatusChannels } from './src/prove.mjs';
import { toCss } from './src/css.mjs';

const root = dirname(fileURLToPath(import.meta.url));
const hue = Number(process.argv[2] ?? NILAM_HUE);

const chosen = solveSemanticHues(hue);
const palette = solvePalette(hue, { semanticHues: chosen.hues });
const { count, failures, notes } = prove(palette);

console.log(`nilam — hue ${hue}, semantics ${JSON.stringify(chosen.hues)}`);
console.log(`  hard-constraint separation floor: ${chosen.worst.toFixed(4)}`);
for (const n of notes) console.log(`  note  ${n}`);

if (failures.length) {
  console.error(`\n  ${count} assertions, ${failures.length} FAILED — nothing written:`);
  for (const f of failures) console.error(`    - ${f}`);
  process.exit(1);
}
console.log(`\n  ${count} assertions, all passed`);

/* The wide-gamut palette: solved against the P3 boundary and proven independently. Both
 * must pass or nothing is written — a P3 block that fails its own contracts is worse than
 * no P3 block, because it only misbehaves on the better screens. */
const p3 = solvePalette(hue, { semanticHues: chosen.hues, gamut: 'display-p3' });
const p3Proof = prove(p3);
console.log(`\n  display-p3: ${p3Proof.count} assertions, ${p3Proof.failures.length ? p3Proof.failures.length + ' FAILED' : 'all passed'}`);
if (p3Proof.failures.length) {
  for (const f of p3Proof.failures) console.error(`    - ${f}`);
  process.exit(1);
}

/* The tokens. */
const tokens = toCss(palette, { assertions: count + p3Proof.count, p3 });
writeFileSync(join(root, 'nilam.tokens.css'), tokens);

/* The single-import convenience build, concatenated from the parts so it cannot drift
 * from them. Assembling it by hand is how achroma shipped a component layer that was
 * in the repo and not in the package. */
const parts = ['nilam.motion.css', 'nilam.scale.css', 'nilam.base.css', 'nilam.components.css'];
const bundle = [
  `/* nilam — the whole system in one import. GENERATED by build.mjs; do not edit.\n`
  + ` *\n`
  + ` * Concatenated from: nilam.tokens.css (solved) + ${parts.join(' + ')}.\n`
  + ` * Import the parts individually if you want the tokens without the components.\n`
  + ` */\n`,
  tokens,
  ...parts.map((p) => `/* ── ${p} ${'─'.repeat(Math.max(0, 66 - p.length))} */\n\n${readFileSync(join(root, p), 'utf8')}`),
].join('\n');
writeFileSync(join(root, 'nilam.css'), bundle);

/* The demo palette, so the demo pages and the package can never disagree. */
writeFileSync(join(root, 'demo/palette.css'), tokens);

const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(1)} kB`;
console.log(`\n  wrote nilam.tokens.css   ${kb(tokens)}`);
console.log(`  wrote nilam.css          ${kb(bundle)}`);
console.log(`  wrote demo/palette.css   ${kb(tokens)}`);
