"""Serve the package's own files from the docs site.

The site dogfoods nilam: the buttons, cards, notes and swatches on these pages are
painted by the stylesheets npm publishes, and the tabs, menu, combobox and slider are
driven by the module npm publishes. So the build has to reach OUTSIDE docs_dir.

The alternative was to copy nilam.tokens.css and friends into docs/. That was rejected:
nilam.tokens.css and nilam.css are GENERATED by build.mjs, and a second copy under
docs/ is a copy that goes stale the first time the solver changes. CI would not catch
it either — `generated-files-are-current` diffs the repo against a rebuild, and a stale
duplicate in docs/ diffs clean against itself.

Adding mkdocs File objects instead means one file on disk, served twice.

The paths are asserted rather than assumed: a missing file raises here and fails the
build, instead of publishing a site whose every colour silently falls back to the
browser default.
"""

from pathlib import Path

from mkdocs.structure.files import File

# Stylesheets, in the order extra_css lists them. nilam.base.css is absent on purpose —
# see the note at the top of docs/stylesheets/extra.css. nilam.css (the whole-system
# bundle) is here for demo/index.html, which imports it directly.
ASSETS = (
    "nilam.tokens.css",
    "nilam.scale.css",
    "nilam.components.css",
    "nilam.widgets.css",
    "nilam.css",
    "assets/hero-light.svg",
    "assets/hero-dark.svg",
    # The showcase page, published as-is. It is the one page on the site that loads
    # nilam.css whole, base layer included, with no material CSS anywhere near it.
    "demo/index.html",
    # The keyboard layer. Relative imports inside these files resolve against the
    # module's own URL, so the directory shape has to survive the copy — which is why
    # they keep their repo paths rather than being flattened.
    "src/behaviours/index.mjs",
    "src/behaviours/roving.mjs",
    "src/behaviours/tabs.mjs",
    "src/behaviours/menu.mjs",
    "src/behaviours/combobox.mjs",
    "src/behaviours/slider.mjs",
)


def on_files(files, config):
    root = Path(config["config_file_path"]).parent

    for relative in ASSETS:
        if not (root / relative).is_file():
            raise FileNotFoundError(
                f"nilam_assets hook: {relative} is missing from {root}. "
                "The docs site is styled by the shipped stylesheets; without it every "
                "colour on the site falls back to the browser default."
            )
        files.append(
            File(
                relative,
                src_dir=str(root),
                dest_dir=config["site_dir"],
                use_directory_urls=config["use_directory_urls"],
            )
        )

    return files
