/* nilam — the CSS emitter.
 *
 * Lifted out of cli.mjs so the build, the CLI and anyone importing the package all go
 * through one code path. When this lived in the CLI, the demo palette and the shipped
 * stylesheet were generated by different code — which is how two things that must
 * agree quietly stop agreeing.
 *
 * ── why light-dark() and not two blocks ──────────────────────────────────────
 *
 * The obvious emit is a :root block, a .dark block, and a prefers-color-scheme copy
 * of the dark block. Three copies of eighty tokens, and the third one exists only
 * because a media query cannot join a selector list.
 *
 * light-dark() collapses it to one. It has been Baseline since 2024, it keys off the
 * inherited color-scheme, and it buys something the class approach cannot do at all:
 * NESTED THEMES. Put color-scheme:dark on a single card inside a light page and every
 * token inside that card flips, because custom-property substitution resolves against
 * the element that consumes the value, not the one that declared it. With .dark blocks
 * you would have to redeclare all eighty tokens on the card to get the same effect.
 *
 * The cost is honest: no fallback. A browser without light-dark() gets no colours at
 * all rather than degraded colours. In 2026 that is the right trade, and the test
 * suite asserts the function is actually used so this decision cannot rot silently.
 */

import { fmt, fmtIn } from './colour.mjs';
import { inkFor } from './solve.mjs';

const FAMILIES = ['neutral', 'brand', 'danger', 'warn', 'ok', 'info'];

/* Layer order, declared once and up front. Anything the consumer writes UNLAYERED
 * beats all of it — which is the point. A design system that needs !important to
 * override is a design system people fork. */
/* nilam.motion is FIRST, and only for the reason below.
 *
 * For NORMAL declarations, a later layer wins. For !IMPORTANT declarations the order is
 * REVERSED, so an earlier layer wins. That reversal is the whole point of the first slot:
 * nilam.base's reduced-motion rule sets `animation-duration: 0.01ms !important` on *, and the
 * loaders need to escape it, because a frozen spinner does not read as reduced motion — it
 * reads as an app that has hung.
 *
 * The exemption originally lived in nilam.components, one layer LATER, on the assumption that
 * later still wins. It does not, for important declarations, so every loader froze and the
 * comment claiming otherwise was wrong for three releases. Measured, not reasoned: spinner,
 * bar and skeleton all reported 1e-05s with 1 iteration under reduce. */
export const LAYERS = '@layer nilam.motion, nilam.tokens, nilam.base, nilam.components, nilam.utilities;';

const pair = (name, light, dark, gamut = 'srgb') =>
  `    --${name}: light-dark(${fmtIn(light, gamut)}, ${fmtIn(dark, gamut)});`;

const family = (palette, name, gamut = 'srgb') => {
  const l = palette.light[name];
  const d = palette.dark[name];

  const steps = Array.from({ length: 12 }, (_, i) => i + 1)
    .map((n) => pair(`${name}-${n}`, l[n], d[n], gamut)).join('\n');

  /* --*-ink is the token nobody else ships and everybody needs: whichever of
   * near-white or near-black is legible on step 9, decided per hue AND per mode.
   * White on the violet solid, black on the amber one, black on the dark-mode glow.
   * `color: white` hard-coded onto a filled button is the most common contrast bug
   * in every system I read. */
  const ink = pair(`${name}-ink`, inkFor(l[9]), inkFor(d[9]), gamut);

  /* The card, and the only surface carrying no tint at all. In light mode the page is
   * tinted and the card is pure white: the tint reads as LIGHT precisely because the
   * thing beside it has none. The eye is comparing, not measuring. */
  const surface = name === 'neutral' ? `\n${pair('surface', l.surface, d.surface, gamut)}` : '';

  return `    /* ${name} */\n${steps}\n${ink}${surface}`;
};

export function toCss(palette, { selector = ':root', assertions = null, p3 = null } = {}) {
  const count = assertions == null ? '' : `${assertions} assertions hold over these exact\n * values; edit one by hand and none of them do.\n *`;

  return `/* nilam — GENERATED. Do not hand-edit; change the hue and re-solve.
 *
 *   npx nilam ${palette.brandHue} --css=nilam.tokens.css
 *
 * brand hue ${palette.brandHue} (नीलम, sapphire) · semantics ${JSON.stringify(palette.semanticHues)}
 *
 * Every lightness here was found by inverting a contrast requirement, not chosen. The
 * semantic hues were chosen to maximise the smallest pairwise separation across normal
 * vision, protanopia, deuteranopia and tritanopia.
 * ${count}
 * Role model (Radix's — it is good design and there was no reason to reinvent it):
 *   1  page              7  border normal   (WCAG 1.4.11, 3:1)
 *   2  subtle page       8  border hover
 *   3  component rest    9  solid           (the brand moment)
 *   4  component hover  10  solid hover
 *   5  component active 11  text low        (WCAG 1.4.3, 4.5:1)
 *   6  border subtle    12  text high       (7:1)
 *
 * STEP 9 DIFFERS BY MODE, deliberately. A filled button inverts the polarity of the
 * page it sits on: a dark object with light text on a light page, a light object with
 * dark text on a dark one. So always pair it with --<family>-ink and never a literal
 * white. In dark mode step 9 is the GLOW — L 0.66, the lightness Zima Blue and the
 * Telepathy accent both happen to share.
 *
 * THEMING. color-scheme drives everything, so:
 *   <html>                  follows the OS
 *   <html class="dark">     forced dark
 *   <html class="light">    forced light
 *   <div class="dark">      just that subtree, tokens and all
 */

${LAYERS}

@layer nilam.tokens {
  ${selector} {
    /* Both keywords, so an unstyled page follows the OS. The classes below narrow it. */
    color-scheme: light dark;

${FAMILIES.map((f) => family(palette, f)).join('\n\n')}
  }

  /* Forcing a mode is one declaration, not a second copy of the palette. These work
     on any element, which is what makes a dark island on a light page free. */
  .light, [data-theme='light'] { color-scheme: light; }
  .dark,  [data-theme='dark']  { color-scheme: dark; }
}
${p3 ? p3Block(p3, selector) : ''}`;
}

/* ── the wide-gamut override ──────────────────────────────────────────────
 *
 * A SECOND SOLVED PALETTE, not a filter over the first, and not an unclamped oklch() left
 * for the browser to gamut-map. Both of those shortcuts hand the final value to code that
 * never measured it: CSS gamut mapping is the browser's algorithm, it may move lightness to
 * preserve hue, and it therefore changes the contrast ratio by an amount nothing here
 * checked. This block was solved against the P3 boundary and proven against P3 luminance —
 * 500 assertions, the same 500 the sRGB palette passes.
 *
 * color(display-p3 …) rather than oklch(), deliberately. oklch() is gamut-independent and
 * would be re-mapped by the browser; naming the space pins the value so the emitted colour
 * is the colour that was proven.
 *
 * Values are unchanged where P3 buys nothing. Measured: +8% chroma at the two brand moments
 * and +13-18% on the statuses, and only +2% below L 0.5 at hue 285.
 */
function p3Block(palette, selector) {
  return `
/* Wide gamut. A separately solved and separately proven palette — see src/css.mjs. */
@media (color-gamut: p3) {
  @layer nilam.tokens {
    ${selector} {
${FAMILIES.map((f) => family(palette, f, 'display-p3')).join('\n\n')}
    }
  }
}
`;
}
