/* nilam — the CSS emitter.
 *
 * Lifted out of cli.mjs so the build, the CLI and anyone importing the package all go
 * through one code path. When this lived in the CLI, the demo palette and the shipped
 * stylesheet were generated by different code — which is how two things that must
 * agree quietly stop agreeing.
 *
 * ── why light-dark() and not two blocks ──────────────────────────────────────
 *
 * The obvious emit is a :root block, a .dark block, and a prefers-color-scheme copy
 * of the dark block. Three copies of eighty tokens, and the third one exists only
 * because a media query cannot join a selector list.
 *
 * light-dark() collapses it to one. It has been Baseline since 2024, it keys off the
 * inherited color-scheme, and it buys something the class approach cannot do at all:
 * NESTED THEMES. Put color-scheme:dark on a single card inside a light page and every
 * token inside that card flips, because custom-property substitution resolves against
 * the element that consumes the value, not the one that declared it. With .dark blocks
 * you would have to redeclare all eighty tokens on the card to get the same effect.
 *
 * The cost is honest: no fallback. A browser without light-dark() gets no colours at
 * all rather than degraded colours. In 2026 that is the right trade, and the test
 * suite asserts the function is actually used so this decision cannot rot silently.
 */

import { fmt } from './colour.mjs';
import { inkFor } from './solve.mjs';

const FAMILIES = ['neutral', 'brand', 'danger', 'warn', 'ok', 'info'];

/* Layer order, declared once and up front. Anything the consumer writes UNLAYERED
 * beats all of it — which is the point. A design system that needs !important to
 * override is a design system people fork. */
export const LAYERS = '@layer nilam.tokens, nilam.base, nilam.components, nilam.utilities;';

const pair = (name, light, dark) => `    --${name}: light-dark(${fmt(light)}, ${fmt(dark)});`;

const family = (palette, name) => {
  const l = palette.light[name];
  const d = palette.dark[name];

  const steps = Array.from({ length: 12 }, (_, i) => i + 1)
    .map((n) => pair(`${name}-${n}`, l[n], d[n])).join('\n');

  /* --*-ink is the token nobody else ships and everybody needs: whichever of
   * near-white or near-black is legible on step 9, decided per hue AND per mode.
   * White on the violet solid, black on the amber one, black on the dark-mode glow.
   * `color: white` hard-coded onto a filled button is the most common contrast bug
   * in every system I read. */
  const ink = pair(`${name}-ink`, inkFor(l[9]), inkFor(d[9]));

  /* The card, and the only surface carrying no tint at all. In light mode the page is
   * tinted and the card is pure white: the tint reads as LIGHT precisely because the
   * thing beside it has none. The eye is comparing, not measuring. */
  const surface = name === 'neutral' ? `\n${pair('surface', l.surface, d.surface)}` : '';

  return `    /* ${name} */\n${steps}\n${ink}${surface}`;
};

export function toCss(palette, { selector = ':root', assertions = null } = {}) {
  const count = assertions == null ? '' : `${assertions} assertions hold over these exact\n * values; edit one by hand and none of them do.\n *`;

  return `/* nilam — GENERATED. Do not hand-edit; change the hue and re-solve.
 *
 *   npx nilam ${palette.brandHue} --css=nilam.tokens.css
 *
 * brand hue ${palette.brandHue} (नीलम, sapphire) · semantics ${JSON.stringify(palette.semanticHues)}
 *
 * Every lightness here was found by inverting a contrast requirement, not chosen. The
 * semantic hues were chosen to maximise the smallest pairwise separation across normal
 * vision, protanopia, deuteranopia and tritanopia.
 * ${count}
 * Role model (Radix's — it is good design and there was no reason to reinvent it):
 *   1  page              7  border normal   (WCAG 1.4.11, 3:1)
 *   2  subtle page       8  border hover
 *   3  component rest    9  solid           (the brand moment)
 *   4  component hover  10  solid hover
 *   5  component active 11  text low        (WCAG 1.4.3, 4.5:1)
 *   6  border subtle    12  text high       (7:1)
 *
 * STEP 9 DIFFERS BY MODE, deliberately. A filled button inverts the polarity of the
 * page it sits on: a dark object with light text on a light page, a light object with
 * dark text on a dark one. So always pair it with --<family>-ink and never a literal
 * white. In dark mode step 9 is the GLOW — L 0.66, the lightness Zima Blue and the
 * Telepathy accent both happen to share.
 *
 * THEMING. color-scheme drives everything, so:
 *   <html>                  follows the OS
 *   <html class="dark">     forced dark
 *   <html class="light">    forced light
 *   <div class="dark">      just that subtree, tokens and all
 */

${LAYERS}

@layer nilam.tokens {
  ${selector} {
    /* Both keywords, so an unstyled page follows the OS. The classes below narrow it. */
    color-scheme: light dark;

${FAMILIES.map((f) => family(palette, f)).join('\n\n')}
  }

  /* Forcing a mode is one declaration, not a second copy of the palette. These work
     on any element, which is what makes a dark island on a light page free. */
  .light, [data-theme='light'] { color-scheme: light; }
  .dark,  [data-theme='dark']  { color-scheme: dark; }
}
`;
}
